# Generated by Django 4.2.4 on 2023-08-19 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('code_files', '0005_remove_codecheck_file_delete_checklog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DONE', 'Done'), ('IN_CHECKING', 'In checking'), ('UNCHECKED', 'Unchecked')], default='UNCHECKED', max_length=11)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_files.uploadedfile')),
            ],
        ),
        migrations.CreateModel(
            name='CheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_text', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_checker.codecheck')),
            ],
        ),
    ]
