# Generated by Django 4.2.4 on 2023-08-20 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_files', '0006_alter_uploadedfile_options_alter_uploadedfile_file_and_more'),
        ('code_checker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklog',
            options={'verbose_name': 'Check Log', 'verbose_name_plural': 'Check Logs'},
        ),
        migrations.AlterModelOptions(
            name='codecheck',
            options={'verbose_name': 'Code Check', 'verbose_name_plural': 'Code Checks'},
        ),
        migrations.AddField(
            model_name='codecheck',
            name='is_notified',
            field=models.BooleanField(default=False, verbose_name='User is notified by email'),
        ),
        migrations.AlterField(
            model_name='checklog',
            name='code_check',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_checker.codecheck', verbose_name='Code Check'),
        ),
        migrations.AlterField(
            model_name='checklog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='checklog',
            name='log_text',
            field=models.TextField(max_length=5000, verbose_name='Log message'),
        ),
        migrations.AlterField(
            model_name='codecheck',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_files.uploadedfile', verbose_name='Uploaded File'),
        ),
        migrations.AlterField(
            model_name='codecheck',
            name='status',
            field=models.CharField(choices=[('DONE', 'Done'), ('IN_CHECKING', 'In checking'), ('UNCHECKED', 'Unchecked')], default='UNCHECKED', max_length=11, verbose_name='Check status'),
        ),
        migrations.AlterField(
            model_name='codecheck',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
    ]
