# Generated by Django 4.2.4 on 2023-08-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_checker', '0003_codecheck_last_check_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklog',
            name='log_text',
            field=models.TextField(max_length=8000, verbose_name='Log message'),
        ),
        migrations.AlterField(
            model_name='codecheck',
            name='last_check_result',
            field=models.TextField(default='Without problems', max_length=8000, verbose_name='Last check result'),
        ),
    ]
