# Generated by Django 4.2.4 on 2023-08-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_files', '0003_codecheck_checklog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='is_checked',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='is_new',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='state',
            field=models.CharField(choices=[('NEW', 'New'), ('OVERWRITTEN', 'Overwritten'), ('OLD', 'Old')], default='New', max_length=11),
        ),
    ]
