# Generated by Django 4.2.4 on 2023-08-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_files', '0004_remove_uploadedfile_is_checked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codecheck',
            name='file',
        ),
        migrations.DeleteModel(
            name='CheckLog',
        ),
        migrations.DeleteModel(
            name='CodeCheck',
        ),
    ]
