# Generated by Django 4.2.4 on 2023-08-20 19:07

import code_files.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('code_files', '0005_remove_codecheck_file_delete_checklog_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={'verbose_name': 'Uploaded File', 'verbose_name_plural': 'Uploaded Files'},
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=code_files.models.user_directory_path, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='filename',
            field=models.CharField(max_length=80, verbose_name='Filename'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='state',
            field=models.CharField(choices=[('NEW', 'New'), ('OVERWRITTEN', 'Overwritten'), ('OLD', 'Old')], default='New', max_length=11, verbose_name='File state'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
